Avoid "NoMethodError" exception on Windows Server 2008R2
On Windows Server 2008R2, windows-exporter plugin fails to collect
CPU metrics with an error message like this:

    [error] #0 undefined method `value' for nilNilClass

... because older Windows does not export some metrics (e.g.
`counters['Clock Interrupts/sec']` is nil on 2008R2).

This patch fixes the error by providing NullPerfCounter as a
default fallback value.

Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>